---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: dev
        type: webserver
      annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9113"
    spec:
      containers:
        - name: nginx-webserver
          image: xkags/nginx-demo
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.01"
            limits:
              memory: "64Mi"
          env:
            - name: PORT
              value: "80"
        - image: nginx/nginx-prometheus-exporter:latest
          name: nginx-prometheus-exporter
          args:
            - "--nginx.scrape-uri=http://localhost:80/stub_status"
          ports:
            - name: metrics
              containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    app: nginx
